### ISSUE TITLE
Help..

### ISSUE THREAD

**Issue by kushal-17** [xtr4nge/FruityDC#1]
When it is going to be release sir as you revealed it at BHEU 2019 please upload it if possible.

**Comment by xtr4nge** [comment]
Hi kushal-17, I hope you are well.
I am working on it right now. I did a lot of changes from my original idea. I will try to release it as soon as possible, but I would say that an alpha is almost ready.

Regards,
xtr4nge

**Comment by kushal-17** [comment]
Hello sir,


                  I hope you are also fine and doing well.Thanks for
replying... And take care sir and ya don't want that for malicious purpose
just for knowledge..and sir can you help me with all as I want my career in
ethicals and can you guide me with anything ...?
